[profile.default]
src = "src"
out = "out"
script = "script"
libs = ["lib", "node_modules"]
solc = "0.8.26"                # to have cancun support
evm_version = 'cancun'         # by default
optimizer = true
optimizer_runs = 99999

[rpc_endpoints]
# MAINNET
mainnet-arbitrum = "${ARBITRUM_MAINNET_RPC}"
mainnet-blast = "${BLAST_MAINNET_RPC}"
mainnet-ethereum = "${ETHEREUM_MAINNET_RPC}"
mainnet-linea = "${LINEA_MAINNET_RPC}"
mainnet-manta-pacific = "${MANTA_PACIFIC_MAINNET_RPC}"
mainnet-mode = "${MODE_MAINNET_RPC}"
mainnet-optimism = "${OPTIMISM_MAINNET_RPC}"
mainnet-scroll = "${SCROLL_MAINNET_RPC}"

# SEPOLIA
sepolia-arbitrum = "${ARBITRUM_SEPOLIA_RPC}"
sepolia-blast = "${BLAST_SEPOLIA_RPC}"
sepolia-ethereum = "${ETHEREUM_SEPOLIA_RPC}"
sepolia-linea = "${LINEA_SEPOLIA_RPC}"
sepolia-manta-pacific = "${MANTA_PACIFIC_SEPOLIA_RPC}"
sepolia-mode = "${MODE_SEPOLIA_RPC}"
sepolia-optimism = "${OPTIMISM_SEPOLIA_RPC}"
sepolia-scroll = "${SCROLL_SEPOLIA_RPC}"
[etherscan]
# MAINNET
mainnet-arbitrum = { key = "${ARBITRUM_MAINNET_ETHERSCAN_KEY}" }
mainnet-blast = { key = "${BLAST_MAINNET_ETHERSCAN_KEY}" }
mainnet-ethereum = { key = "${ETHEREUM_MAINNET_ETHERSCAN_KEY}" }
mainnet-linea = { key = "${LINEA_MAINNET_ETHERSCAN_KEY}" }
mainnet-manta-pacific = { key = "${MANTA_PACIFIC_MAINNET_ETHERSCAN_KEY}" }
mainnet-mode = { key = "${MODE_MAINNET_ETHERSCAN_KEY}" }
mainnet-optimism = { key = "${OPTIMISM_MAINNET_ETHERSCAN_KEY}" }
mainnet-scroll = { key = "${SCROLL_MAINNET_ETHERSCAN_KEY}" }

# SEPOLIA
sepolia-arbitrum = { key = "${ARBITRUM_SEPOLIA_ETHERSCAN_KEY}" }
sepolia-blast = { key = "${BLAST_SEPOLIA_ETHERSCAN_KEY}" }
sepolia-ethereum = { key = "${ETHEREUM_SEPOLIA_ETHERSCAN_KEY}" }
sepolia-linea = { key = "${LINEA_SEPOLIA_ETHERSCAN_KEY}" }
sepolia-manta-pacific = { key = "${MANTA_PACIFIC_SEPOLIA_ETHERSCAN_KEY}" }
sepolia-mode = { key = "${MODE_SEPOLIA_ETHERSCAN_KEY}" }
sepolia-optimism = { key = "${OPTIMISM_SEPOLIA_ETHERSCAN_KEY}" }
sepolia-scroll = { key = "${SCROLL_SEPOLIA_ETHERSCAN_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
