[profile.default]
src = "src"
out = "out"
script = "script"
libs = ["lib", "dependencies", "node_modules"]
solc = "0.8.26"                                # to have cancun support
evm_version = 'cancun'                         # by default
optimizer = true
optimizer_runs = 99999

[rpc_endpoints]
# MAINNET
mainnet-arbitrum = "${ARBITRUM_MAINNET_RPC}"
mainnet-blast = "${BLAST_MAINNET_RPC}"
mainnet-ethereum = "${ETHEREUM_MAINNET_RPC}"
mainnet-linea = "${LINEA_MAINNET_RPC}"
mainnet-manta-pacific = "${MANTA_PACIFIC_MAINNET_RPC}"
mainnet-mode = "${MODE_MAINNET_RPC}"
mainnet-optimism = "${OPTIMISM_MAINNET_RPC}"
mainnet-scroll = "${SCROLL_MAINNET_RPC}"

# SEPOLIA
sepolia-arbitrum = "${ARBITRUM_SEPOLIA_RPC}"
sepolia-blast = "${BLAST_SEPOLIA_RPC}"
sepolia-ethereum = "${ETHEREUM_SEPOLIA_RPC}"
sepolia-linea = "${LINEA_SEPOLIA_RPC}"
sepolia-manta-pacific = "${MANTA_PACIFIC_SEPOLIA_RPC}"
sepolia-mode = "${MODE_SEPOLIA_RPC}"
sepolia-optimism = "${OPTIMISM_SEPOLIA_RPC}"
sepolia-scroll = "${SCROLL_SEPOLIA_RPC}"

[etherscan]
# MAINNET
mainnet-arbitrum = { key = "${ARBITRUM_MAINNET_ETHERSCAN_KEY}" }                               # arbiscan
mainnet-blast = { key = "${BLAST_MAINNET_ETHERSCAN_KEY}" }                                     # blastscan
mainnet-ethereum = { key = "${ETHEREUM_MAINNET_ETHERSCAN_KEY}" }                               # etherscan
mainnet-linea = { key = "${LINEA_MAINNET_ETHERSCAN_KEY}" }                                     # lineascan
mainnet-manta-pacific = { key = "EMPTY", url = "https://pacific-explorer.manta.network/api?" } # blockscout
mainnet-mode = { key = "EMPTY", url = "https://explorer.mode.network/api?" }                   # blockscout
mainnet-optimism = { key = "${OPTIMISM_MAINNET_ETHERSCAN_KEY}" }                               # optimistic.etherscan
mainnet-scroll = { key = "${SCROLL_MAINNET_ETHERSCAN_KEY}" }                                   # scrollscan

# SEPOLIA
sepolia-arbitrum = { key = "${ARBITRUM_SEPOLIA_ETHERSCAN_KEY}" }
sepolia-blast = { key = "${BLAST_SEPOLIA_ETHERSCAN_KEY}" }
sepolia-ethereum = { key = "${ETHEREUM_SEPOLIA_ETHERSCAN_KEY}" }
sepolia-linea = { key = "${LINEA_SEPOLIA_ETHERSCAN_KEY}" }
sepolia-manta-pacific = { key = "EMPTY", url = "https://pacific-explorer.sepolia-testnet.manta.network/api?" }
sepolia-mode = { key = "EMPTY", url = "https://sepolia.explorer.mode.network/api?" }
sepolia-optimism = { key = "${OPTIMISM_SEPOLIA_ETHERSCAN_KEY}" }
sepolia-scroll = { key = "${SCROLL_SEPOLIA_ETHERSCAN_KEY}" }

[fmt]
line_length = 120
tab_width = 2
bracket_spacing = true
quote_style = "single"
ignore = ['./src/external/**/*']

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[dependencies]
solady = "0.0.230"
forge-std = "1.9.1"
openzeppelin-foundry-upgrades = "0.3.1"
"@openzeppelin-contracts" = "5.0.2"
"@openzeppelin-contracts-upgradeable" = "5.0.2"
"@openzeppelin-contracts-v4" = { version = "4.9.6", url = "https://github.com/OpenZeppelin/openzeppelin-contracts/archive/refs/tags/v4.9.6.zip" }
"@openzeppelin-contracts-upgradeable-v4" = { version = "4.9.6", url = "https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/archive/refs/tags/v4.9.6.zip" }
