name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  file-list:
    name: branch with codes
    runs-on: ubuntu-latest

    outputs:
      file-list: ${{ steps.file-list.outputs.file-list }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - id: file-list
        run: |
          echo "$(git ls-files | grep -vE 'src/\w+' | jq -R . | jq -s .)" >> "$GITHUB_OUTPUT"

  make-clean:
    name: branch with codes
    runs-on: ubuntu-latest
    needs: file-list

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: create branch and push
        uses: EndBug/add-and-commit@v9
        with:
          remove: ${{ needs.file-list.outputs.file-list }}
          new_branch: 'clean'
          message: 'cleaned ${{ github.sha }}'
