name: Make Clean Branch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clean-branch:
    name: make clean branch
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: clean

      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            src

      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "cleaned $GITHUB_SHA"
          git push origin clean
