name: Make Clean Branch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  file-list:
    name: make file list to remove
    runs-on: ubuntu-latest

    outputs:
      file-list: ${{ steps.file-list.outputs.file-list }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Make file list to remove
        id: file-list
        run: |
          echo "FILE_LIST=$(git ls-files | grep -vE 'src/\w+' | jq -R . | jq -sc .)" >> "$GITHUB_OUTPUT"

      - name: Check output var
        run: |
          echo ${{steps.file-list.outputs.FILE_LIST}}

  make-clean:
    name: make clean branch
    runs-on: ubuntu-latest
    needs: file-list

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: create branch and push
        uses: EndBug/add-and-commit@v9
        with:
          remove: ${{ needs.file-list.outputs.file-list.FILE_LIST }}
          new_branch: 'clean'
          message: 'cleaned ${{ github.sha }}'
