name: Make Clean Branch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  file-list:
    name: make file list to remove
    runs-on: ubuntu-latest

    outputs:
      list: ${{ steps.file-list.outputs.list }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Make file list to remove
        id: file-list
        run: |
          echo "list=$(git ls-files | grep -vE 'src/\w+' | jq -R . | jq -sc .)" >> "$GITHUB_OUTPUT"

      - name: Check output var
        run: |
          echo ${{steps.file-list.outputs.list}}

  make-clean:
    name: make clean branch
    runs-on: ubuntu-latest
    needs: file-list

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Check input var
        run: |
          echo ${{ needs.file-list.outputs.list }}

      - name: create branch and push
        uses: EndBug/add-and-commit@v9
        with:
          remove: '${{ needs.file-list.outputs.list }}'
          push: 'origin clean --force'
          new_branch: 'clean'
          message: 'cleaned ${{ github.sha }}'
