name: Make Clean Branch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clean-branch:
    name: make clean branch
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Make file list to remove
        id: file-list
        run: |
          echo "list=$(git ls-files | grep -vE 'src/\w+' | jq -R . | jq -sc .)" >> "$GITHUB_OUTPUT"

      - name: Check file list
        run: |
          echo ${{steps.file-list.outputs.list}}

      - name: create branch and push
        uses: EndBug/add-and-commit@v9
        with:
          remove: '${{ steps.file-list.outputs.list }}'
          push: 'origin clean --set-upstream --force'
          new_branch: 'clean'
          message: 'cleaned ${{ github.sha }}'
