name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  push:
    strategy:
      fail-fast: true

    name: branch with codes
    runs-on: arc-runner-set
    container: node:20

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: remove all except src
        run: |
          rm -rf $(ls -a | grep -v src)

      - name: create branch and push
        uses: EndBug/add-and-commit@v9
        with:
          new_branch: 'clean'
          message: 'cleaned ${{ github.sha }}'
