name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CI: true
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: test
    runs-on: arc-runner-set
    container: node:20

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_REPO_READER }}
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Yarn Install
        run: yarn install

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run Soldeer install
        run: |
          forge soldeer install

      - name: Show Forge version
        run: |
          forge --version

      - name: Run linter checks
        run: |
          yarn lint:check
        id: lint

      - name: Run Forge build
        run: |
          forge build
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test

      - name: Run Forge coverage
        run: |
          apt-get update
          apt-get -y install lcov
          ./tools/coverage.sh
        id: coverage

      - name: Upload to codecov.io
        if: ${{ github.repository == 'mitosis-org/protocol' }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true
